name: Update Image Metadata

on:
  push:
    branches:
      - main
    paths:
      - 'assets/**.jpg'
      - 'assets/**.png'

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch previous commit for diff

      - name: Cache ExifTool
        id: cache-exiftool
        uses: actions/cache@v4
        with:
          path: /usr/bin/exiftool
          key: exiftool-${{ runner.os }}-13.33
          restore-keys: exiftool-${{ runner.os }}-

      - name: Install ExifTool
        if: steps.cache-exiftool.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y exiftool

      - name: Get changed image files
        id: changed-files
        run: |
          # Get list of changed jpg/png files since last commit
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD -- 'assets/*.jpg' 'assets/*.png' || true)
          echo "files=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Update image metadata
        if: steps.changed-files.outputs.files != ''
        run: |
          # Process only changed files
          echo "${{ steps.changed-files.outputs.files }}" | xargs -r exiftool \
            -Copyright="© Gary McNickle 2025" \
            -XMP:UsageTerms="Licensed under Creative Commons Attribution 4.0 International (https://creativecommons.org/licenses/by/4.0/)" \
            -XMP:Creator="Gary McNickle" \
            -XMP-photoshop:CopyrightStatus=2 \
            -XMP:WebStatement="https://creativecommons.org/licenses/by/4.0/" \
            -overwrite_original \
            -fast

      - name: Check for changes
        id: git-check
        run: |
          if git status --porcelain | grep -E '\.jpg$|\.png$'; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          # Add jpg and png files if they exist, without failing if none match
          find assets -type f \( -name "*.jpg" -o -name "*.png" \) -exec git add {} +
          git commit -m "Updated image metadata with copyright notice, status, and URL [ci skip]"
          git push
